# Generated by Django 5.1.4 on 2025-01-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="text",
            field=models.TextField(default="Default Text because I forgot"),
            preserve_default=False,
        ),
    ]
